# Header
menu:
  Home: 主页

# Content
excerpt_link: 更过
prev: 上一页
next: 下一页
reply: 评论
share: 分享
fancybox: true

# Sidebar
widgets:
- about
- category
- recent_posts
- tag
- tagcloud
- account

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 